#!/bin/bash
#PBS -q default 
#PBS -N admixture600QC15.20.k.6.28.24         
#PBS -o admixture600QC15.20.k.6.28.24.txt     
#PBS -e admixture600QC15.20.k.6.28.24err.txt  
#PBS -l nodes=1:ppn=8         	      
#PBS -l mem=32gb                     
#PBS -l walltime=36:00:00             
#PBS -W group_list=x-ccast-prj-tseaborn                      
#PBS -m ae
#PBS -M alec.christensen@ndsu.edu

cd Admixture
module load admixture/1.3.0
for K in {1..10}; do
  admixture --cv AMix600QCF.bedRandom600.pilotA.bed $K | tee log${K}.out
done

echo "yay all done"
