#!/bin/bash
#PBS -q default 
#PBS -N admixture.k.12.17.24         
#PBS -o admixture.k.12.17.24.txt     
#PBS -e admixture.k.12.17.24err.txt  
#PBS -l nodes=1:ppn=8         	      
#PBS -l mem=32gb                     
#PBS -l walltime=36:00:00             
#PBS -W group_list=x-ccast-prj-tseaborn                      
#PBS -m ae
#PBS -M alec.christensen@ndsu.edu

cd Obj.2_admixture
module load admixture/1.3.0
admixture --cv=10 alldeer_allyears.bed $K | tee log${K}.out

echo "yay all done"

